spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_NAME}?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}

  jwt:
    key: ${SPRING_JWT_KEY}

server:
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always