spring:
  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/musicservice?createDatabaseIfNotExist=true
    username: root
    password: 1515

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    key: 688787d8ff144c502c7f5cffaafe2cc588d86079f9de88304c26b0cb99ce91c6