spring:
  datasource:
    url: jdbc:mysql://localhost:3306/musicservice?createDatabaseIfNotExist=true
    user: root
    password: 1515
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600s
  jwt:
    key: 688787d8ff144c502c7f5cffaafe2cc588d86079f9de88304c26b0cb99ce91c6
    accessTokenExpiration: 900
    refreshTokenExpiration: 7200
  files:
    path: tracks
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
